# Generated by Django 5.1.4 on 2024-12-11 20:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ENGINE', 'Engine'), ('TRANSMISSION', 'Transmission'), ('BRAKES', 'Brakes'), ('SUSPENSION', 'Suspension'), ('WHEELS', 'Wheels'), ('BATTERY', 'Battery'), ('EXHAUST', 'Exhaust'), ('AIR_FILTER', 'Air Filter'), ('FUEL_TANK', 'Fuel Tank')], default='ENGINE', max_length=30)),
                ('quality', models.CharField(choices=[('Used', 'Used'), ('New', 'New'), ('Damaged', 'Damaged'), ('Refurbished', 'Refurbished')], default='New', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('type_parts', models.ManyToManyField(related_name='manufacturers', to='car_parts.carpartcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.carpartcategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.manufacturer')),
            ],
        ),
    ]
