# Generated by Django 5.1.4 on 2024-12-11 21:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='type_parts',
        ),
        migrations.RemoveField(
            model_name='carpart',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='carpart',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='CarPartCategory',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
