# Generated by Django 5.1.4 on 2024-12-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carbrand_name_alter_carmodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
    ]
