# Generated by Django 5.1.4 on 2024-12-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carspecs'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspecs',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='cars.car'),
        ),
    ]
