# Generated by Django 5.1.4 on 2024-12-11 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_carspecs_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
