# Generated by Django 5.1.4 on 2024-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_bench_alter_profile_deadlift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bench',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deadlift',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='squat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
