# Generated by Django 5.1.4 on 2024-12-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_description_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_transmission',
            field=models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], null=True),
        ),
    ]
